-- // Services //
local ServerScriptService = game:GetService("ServerScriptService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
-- // Services //

-- // Folders //
local ClientObjectScripts = ReplicatedStorage.ClientObjects
local ServerObjectScripts = ReplicatedStorage.ServerObjects
local ReplicatedLibrary = ReplicatedStorage.Library
local ServerLibrary = script.Library
-- // Folders //
