-- // Services //
local ServerScriptService = game:GetService("ServerScriptService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
-- // Services //

-- // Folders //
local SharedFolder = ReplicatedStorage.Shared
local ClientObjectScripts = SharedFolder.ClientObjects
local ServerObjectScripts = SharedFolder.ServerObjects
local ReplicatedLibrary = SharedFolder.SharedLibrary
local ServerLibrary = script.Library
-- // Folders //

-- // Modules //

-- // Modules //